"""empty message

Revision ID: 13de7c02dbaa
Revises: 4308bdabbed6
Create Date: 2025-05-12 22:50:23.631348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13de7c02dbaa'
down_revision = '4308bdabbed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_people',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['peoples.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'people_id')
    )
    op.create_table('profile_planet',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'planet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_planet')
    op.drop_table('profile_people')
    # ### end Alembic commands ###
