"""empty message

Revision ID: 6f82acf9d8c5
Revises: 9f660c099e16
Create Date: 2025-05-13 23:04:46.247484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f82acf9d8c5'
down_revision = '9f660c099e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_see_id_key', type_='unique')
        batch_op.drop_column('see_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('see_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_see_id_key', ['see_id'])

    # ### end Alembic commands ###
