"""empty message

Revision ID: ab14990154f6
Revises: c6a0201561c7
Create Date: 2025-05-12 22:48:29.715506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab14990154f6'
down_revision = 'c6a0201561c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('peoples')
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_planet', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.UniqueConstraint('name_planet', name='planets_name_planet_key')
    )
    op.create_table('peoples',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_people', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.UniqueConstraint('name_people', name='peoples_name_people_key')
    )
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey')
    )
    # ### end Alembic commands ###
